class TestData:
    email = "tester_alk@wp.pl"
    gender = "male"
    last_name = "Nowak"
    password = "password123"
    birthdate = "1980-02-28"
    address = "Kaliska 7"
    city = "Warsaw"
    postal_code = "62800"
    state = "Texas"
    phone = "123342123"
    alias = "My home"